# Generated by Django 6.0.4 on 2026-04-17 11:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='hero'),
        ),
    ]
