# Generated by Django 6.0.4 on 2026-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_selected_seats_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='available_seats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
