# Generated by Django 6.0.4 on 2026-04-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_available_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='available_seats',
        ),
    ]
