# Generated by Django 6.0.4 on 2026-04-17 06:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_poster_url_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='columns',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='theatre',
            name='rows',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='posters'),
        ),
    ]
