# Generated by Django 6.0.4 on 2026-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_theatre_columns_theatre_rows_alter_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='available_seats',
        ),
        migrations.AlterField(
            model_name='show',
            name='total_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
