# Generated by Django 6.0.4 on 2026-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_show_available_seats_alter_show_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='available_seats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
