# Generated by Django 6.0.4 on 2026-04-21 06:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_show_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='card_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_premiere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_type',
            field=models.CharField(choices=[('like', 'Like'), ('rating', 'Rating')], default='like', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
