# Generated by Django 6.0.4 on 2026-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_card_subtitle_movie_is_premiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
